use std::{
    any::Any,
    fmt::{Debug, Formatter, Result},
};

use crate::board::{Board, Coord, GameMove, MoveType};
use crate::pieces::piecetype::PieceType;

pub mod chess2;
pub mod fairy;
pub mod piecetype;
pub mod standard;

/// ------------- Pieces -------------

pub trait Piece {
    fn name(&self) -> &str;
    fn color(&self) -> Color;
    fn set_color(&mut self, color: Color);
    fn initial_moves(&self, board: &Board, from: &Coord) -> Vec<GameMove>;
    fn symbol(&self) -> String;

    fn can_carry_piece(&self) -> bool {
        false
    }

    /// Read-only view of this carrier's passenger list, or `None` if
    /// the piece isn't a carrier. Default-`None` so non-carriers don't
    /// need to override. Carriers (Bus, Locomotive, Carriage) override
    /// to expose their internal `Vec<PieceType>`. Used by the move
    /// filter, `find_king` descent, and the PieceInCarrier dispatch.
    fn passengers(&self) -> Option<&[PieceType]> {
        None
    }

    /// Mutable handle on this carrier's passenger list, or `None` for
    /// non-carriers. Used by `make_move` when a passenger enters /
    /// exits / is captured by an enemy boarding.
    fn passengers_mut(&mut self) -> Option<&mut Vec<PieceType>> {
        None
    }

    /// Plan 08: can this piece throw a Switch tile it's standing on?
    /// Default `true` — every piece can. Override to `false` for pieces
    /// the spec disallows (none in v1, but the hook is here so a future
    /// piece definition can disable it without touching `Board::get_moves`).
    fn can_throw_switch(&self) -> bool {
        true
    }

    fn clone_box(&self) -> Box<dyn Piece>;

    /// Called once after a player move lands this piece on its
    /// destination square. Use this to update piece-private state or
    /// flag state on the board: pawn double-push records the
    /// en-passant target, rook/king moves clear castle rights,
    /// Goblin captures transition to `Kidnapping`, etc.
    ///
    /// Calling convention: `&self` is a *clone* of the on-board
    /// piece. Mutating it locally has no effect — the clone is
    /// dropped after this call. If your piece needs to change its
    /// own state on the board, choose one of two patterns:
    ///
    /// - **Rebuild + overwrite** (Skibidi). Clone `self`, mutate
    ///   the clone, then `board_after.set_piece_at(target, ...)`.
    ///   Best for "I want to be a different concrete piece at the
    ///   same square" or "I want to fully replace myself".
    ///
    /// - **In-place mutate via downcast** (Goblin's Free →
    ///   Kidnapping branch). Get a mut handle on the on-board
    ///   piece via `board_after.get_square_mut(target)` and use
    ///   `as_any_mut().downcast_mut::<Self>()` to mutate fields
    ///   directly. Best for "I want to change my own internal state
    ///   but stay the same kind of piece".
    ///
    /// Goblin actually uses both: the Free → Kidnapping branch
    /// downcasts; the Kidnapping → home branch overwrites with the
    /// converted (ex-victim) piece, since "the goblin dies" per spec.
    ///
    /// `board_after` is the post-relocation board; the moved piece
    /// sits at the move's destination, and `board_before` is its
    /// pre-move snapshot.
    fn post_move_effects(
        &self,
        _board_before: &Board,
        _board_after: &mut Board,
        _game_move: &GameMove,
    ) {
        // Default: do nothing
    }

    /// Squares this piece *threatens* to capture from `from`. The result is
    /// independent of the colour of any current occupant — a square in the
    /// returned set is "the piece would capture an enemy piece if one were
    /// here, ignoring the same-colour move filter."
    ///
    /// Differs from `initial_moves` in two important ways:
    /// - It returns only attack targets (squares the piece can capture on),
    ///   not non-capturing moves. Pawns are the canonical case: a forward
    ///   push lands on a square the pawn does *not* attack.
    /// - It must not recurse into board-level queries that themselves call
    ///   `attacks` (e.g. `Board::is_attacked_by`), or `is_in_check` will
    ///   loop forever.
    ///
    /// The default extracts the destination coord from each `MoveTo`,
    /// `Promotion`, and `EnPassant` move generated by `initial_moves`. This
    /// works for most pieces; Pawn, King, Bus, and Skibidi need overrides
    /// (see their files for the why).
    fn attacks(&self, board: &Board, from: &Coord) -> Vec<Coord> {
        self.initial_moves(board, from)
            .into_iter()
            .filter_map(|m| match m.move_type {
                MoveType::MoveTo(c) => Some(c),
                MoveType::Promotion { target, .. } => Some(target),
                MoveType::EnPassant { target, .. } => Some(target),
                _ => None,
            })
            .collect()
    }

    /// Predicate: if this piece (sitting at `from`) reaches `target`,
    /// does that count as a *capture* of whatever is on `target`?
    ///
    /// Default is "yes, anything I attack I also capture." Overrides
    /// are for pieces whose movement reaches a tile without
    /// destroying its occupant — most notably train carts, which roll
    /// onto a same-train cart's tile via chain-following (not
    /// capture). King-safety checks AND captures both call this so a
    /// "phantom" attack doesn't put a king in spurious check.
    ///
    /// Plan 10 will fold this into the movement-stack registry; for
    /// now it's a per-piece hook to keep the train-specific
    /// conditionals out of `is_attacked_by`.
    fn would_capture_at(&self, _board: &Board, _from: &Coord, _target: &Coord) -> bool {
        true
    }

    /// For downcasting support
    fn as_any(&self) -> &dyn Any;
    fn as_any_mut(&mut self) -> &mut dyn Any;
}

impl PartialEq for dyn Piece {
    fn eq(&self, other: &Self) -> bool {
        self.symbol() == other.symbol()
    }
}

impl Debug for dyn Piece {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        write!(f, "{}", self.symbol())
    }
}

impl Clone for Box<dyn Piece> {
    fn clone(&self) -> Box<dyn Piece> {
        self.clone_box()
    }
}

#[derive(Clone, Copy, PartialEq, Debug, serde::Serialize, serde::Deserialize)]
pub enum Color {
    White,
    Black,
    /// Trains and other unaligned actors. Has no opposite (returns itself);
    /// no king of this color exists; can never be the side-to-move.
    Neutral,
}

impl Color {
    /// The opposing side. White ↔ Black; **Neutral is a fixed point**
    /// (`Neutral.opposite() == Neutral`). The fixed point is a
    /// defensive choice — there's no meaningful opposite of "trains
    /// and unaligned actors." Callers that need a real swap must
    /// guarantee non-Neutral input; `apply_environment_reactions`
    /// asserts this before the side-to-move flip, and `validate_move`
    /// rejects a Neutral mover via `WrongTurn`.
    pub fn opposite(&self) -> Color {
        match self {
            Color::White => Color::Black,
            Color::Black => Color::White,
            Color::Neutral => Color::Neutral,
        }
    }
}

impl std::fmt::Display for Color {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Color::White => "white",
            Color::Black => "black",
            Color::Neutral => "neutral",
        })
    }
}
