use std::{
    any::Any,
    fmt::{Debug, Formatter, Result},
};

use crate::board::{Board, Coord, GameMove, MoveType};

pub mod chess2;
pub mod fairy;
pub mod piecetype;
pub mod standard;

/// ------------- Pieces -------------

pub trait Piece {
    fn name(&self) -> &str;
    fn color(&self) -> Color;
    fn set_color(&mut self, color: Color);
    fn initial_moves(&self, board: &Board, from: &Coord) -> Vec<GameMove>;
    fn symbol(&self) -> String;

    fn can_carry_piece(&self) -> bool {
        false
    }

    /// Plan 08: can this piece throw a Switch tile it's standing on?
    /// Default `true` — every piece can. Override to `false` for pieces
    /// the spec disallows (none in v1, but the hook is here so a future
    /// piece definition can disable it without touching `Board::get_moves`).
    fn can_throw_switch(&self) -> bool {
        true
    }

    fn clone_box(&self) -> Box<dyn Piece>;

    fn post_move_effects(
        &mut self,
        _board_before: &Board,
        _board_after: &mut Board,
        _game_move: &GameMove,
    ) {
        // Default: do nothing
    }

    /// Squares this piece *threatens* to capture from `from`. The result is
    /// independent of the colour of any current occupant — a square in the
    /// returned set is "the piece would capture an enemy piece if one were
    /// here, ignoring the same-colour move filter."
    ///
    /// Differs from `initial_moves` in two important ways:
    /// - It returns only attack targets (squares the piece can capture on),
    ///   not non-capturing moves. Pawns are the canonical case: a forward
    ///   push lands on a square the pawn does *not* attack.
    /// - It must not recurse into board-level queries that themselves call
    ///   `attacks` (e.g. `Board::is_attacked_by`), or `is_in_check` will
    ///   loop forever.
    ///
    /// The default extracts the destination coord from each `MoveTo`,
    /// `Promotion`, and `EnPassant` move generated by `initial_moves`. This
    /// works for most pieces; Pawn, King, Bus, and Skibidi need overrides
    /// (see their files for the why).
    fn attacks(&self, board: &Board, from: &Coord) -> Vec<Coord> {
        self.initial_moves(board, from)
            .into_iter()
            .filter_map(|m| match m.move_type {
                MoveType::MoveTo(c) => Some(c),
                MoveType::Promotion { target, .. } => Some(target),
                MoveType::EnPassant { target, .. } => Some(target),
                _ => None,
            })
            .collect()
    }

    /// For downcasting support
    fn as_any(&self) -> &dyn Any;
    fn as_any_mut(&mut self) -> &mut dyn Any;
}

impl PartialEq for dyn Piece {
    fn eq(&self, other: &Self) -> bool {
        self.symbol() == other.symbol()
    }
}

impl Debug for dyn Piece {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        write!(f, "{}", self.symbol())
    }
}

impl Clone for Box<dyn Piece> {
    fn clone(&self) -> Box<dyn Piece> {
        self.clone_box()
    }
}

#[derive(Clone, Copy, PartialEq, Debug, serde::Serialize, serde::Deserialize)]
pub enum Color {
    White,
    Black,
}

impl Color {
    pub fn opposite(&self) -> Color {
        match self {
            Color::White => Color::Black,
            Color::Black => Color::White,
        }
    }
}

impl std::fmt::Display for Color {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Color::White => "white",
            Color::Black => "black",
        })
    }
}
